---
name: lint

on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up py10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install pipx
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          sudo pipx ensurepath --global
      - name: install poetry
        run: |
          pipx install poetry
      - name: install dev packages
        run: |
          poetry install --with dev
      - name: run linters
        run: |
          poetry shell
          .ci/lint.sh

# jobs:
#   isort-lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - uses: jamescurtin/isort-action@master
#   black-lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: psf/black@stable
#         with:
#           options: "-l79"
#   yamllint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: karancode/yamllint-github-action@master
#   flake8:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           sudo apt-get install -y flake8
#           flake8 . --count --show-source --statistics --config=.flake8.cfg
