---
name: release
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up py10
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v3
      - name: build release artifacts
        run: |
          uv build
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
