---
name: release
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up py10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: install pipx
        run: |
          apt update
          apt install pipx
          pipx ensurepath
          pipx ensurepath --global
      - name: install poetry
        run: |
          pipx install poetry
      - name: build release artifacts
        run: |
          poetry build
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
