---
name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up py39
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: build release artifacts
        run: |
          python -m pip install -U pip
          pip install build
          rm -rf build/ dist/ || true
          python -m build .
      - name: create release
        uses: softprops/action-gh-release@v0.1.4
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

